# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custa', '0002_auto_20190308_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custa',
            old_name='base_name',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='custa',
            old_name='sauce_name',
            new_name='sauce',
        ),
        migrations.RenameField(
            model_name='custa',
            old_name='top_name',
            new_name='top',
        ),
        migrations.RenameField(
            model_name='custa',
            old_name='username',
            new_name='user',
        ),
    ]
