# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custa', '0003_auto_20190308_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
    ]
