# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custa', '0004_auto_20190308_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCusta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('custa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custa.Custa')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_details',
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercusta',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custa.Order'),
        ),
    ]
