# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custa', '0005_auto_20190310_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
