# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custa', '0006_auto_20190310_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custa',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
